version: "3.7"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 dbx_to_azure_blob:app
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - AZURE_CONN_STRING=${AZURE_CONN_STRING}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
      - FLASK_APP=dbx_to_azure_blob.py
      - FLASK_DEBUG=
