version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
      - AZURE_CONN_STRING=${AZURE_CONN_STRING}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
      - FLASK_APP=dbx_to_azure_blob.py
      - FLASK_DEBUG=1
