version: "3.7"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 dbx_to_azure_blob:app
    volumes:
      - ./:/usr/src/app
    expose:
      - 5000
    restart: always
    environment:
      - DROPBOX_ACCESS_TOKEN=QkwG-MThZnAAAAAAAAAOx0gIVf2U_A37KVstAwbEWwBkxYaUCZUO6pysOQlx7yUL
      - AZURE_CONN_STRING=${AZURE_CONN_STRING}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
      - FLASK_APP=dbx_to_azure_blob.py
  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - web
